# Generated by Django 4.1.7 on 2023-03-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userClients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSharesData',
        ),
    ]
