# Generated by Django 4.1.7 on 2023-03-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userClients', '0003_usersharesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=225)),
                ('currency_symbol', models.CharField(max_length=50)),
                ('funds', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userClients.userclient')),
            ],
        ),
    ]
