# Generated by Django 4.1.7 on 2023-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userClients', '0004_usercurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrency',
            name='funds',
            field=models.FloatField(),
        ),
    ]
