# Generated by Django 4.1.7 on 2023-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('company_symbol', models.CharField(max_length=50)),
                ('no_of_shares', models.IntegerField()),
                ('share_currency', models.CharField(max_length=25)),
                ('share_price', models.FloatField()),
                ('last_updated_date', models.DateField()),
            ],
        ),
    ]
